fixtures:
    symlinks:
      softhsm: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.17.0
      tea:
        repo: https://github.com/icann-dns/puppet-tea.git
    forge_modules:
